---
title: "Triad Ultimate"
output: html_document
---

Welcome to the league 


## Annoucements 


* __2021.10.31__: Sign ups are open for Winter League! Looking forward to seeing your beautiful faces out there!

</br>

## To answer your questions.... 

We've heard a couple of questions come up when talking with players who haven't played league with us before, so we wanted to address them here:


* Skill level:
    * We are taking all skill levels and are excited to see Ultimate grow in the Triad area.
    * We will be playing by USAU rules, and the captains are there to help educated and ensure everyone has a good time.
* If a player shows up late to a game because of work can they still play?
    * yep! Just let your captain know so they can plan accordingly.
* What can I do if I cannot afford league dues?
    * We want to make sure anyone can play, regardless of financial situations. Please reach out to <triadultimate@gmail.com> and we will find a way to make it work.

## How do I keep up to date on information?

1. Join the Slack channel!  
    * Download Slack
    * [Follow this link to join](https://join.slack.com/t/triadareaultimate/shared_invite/zt-vtdsxl1t-hl4Ns2Phwg~VmW2~sfjUlg) 
1. Check your email  
    * If you did not get an email reach out to <triadultimate@gmail.com> so we can update your contact information.




</br>

## COVID Protocols 

We will continue to monitor the situtation as we get closer to the start of league. During Summer League we were very proud of the community for being up front, communicating to the community at large and getting tested when they were alerted to being exposed. We expect that we will continue to have that same level of maturity continue throughout our leagues.

__General Operating Guidelines__  

* Whenever possible, maintain a safe distance and be respectful of people.
* Masks are not required, but you are welcome to wear one if you desire.
* Proof of vaccination is not required, but if you feel sick or test positive, please __stay home__ and __let your captains know__ as soon as possible so that we can ensure we are not spreading diseases.

__Closing Comments__ 

If there are material changes to guidance issued by the CDC during the registration period, or during the season, the league rules may be amended to reflect any updates. Any changes will be communicated to all participants in the league. 

We appreciate your cooperation with our game play modifications this summer and look forward to returning to standard league rules and non-modified game play in the near future.

</br>

## Questions or concerns?

### Where does your money go?

Thank you so much for promptly paying league dues. Our goal is always to keep costs as low as possible to ensure fiances are not a barrier to play.

The dues go to the following items:  

* Reserving fields
* Purchasing general liability insurance  
* Super cool jersey
  * Materials + Printing costs + Design fee from exclusive design artist
* Small buffer to ensure we can cover unforeseen costs


### Other Questions?

If you have any questions, comments, concerns, suggestions, exhortations, or exclamations please don't hesitate to reach out to <triadultimate@gmail.com> 

If you have would like to assist in maintenance and context development for this site and/or the league, please also feel free to reach out!


